# fly.toml app configuration file generated for altair-piu1u on 2024-03-29T12:46:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'altair-piu1u'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['altair']

[[vm]]
  size = 'shared-cpu-1x'

[deploy]
  strategy = "immediate"

