---
name: Deploy

on:
    push:
        branches:
            - main

permissions:
    contents: read
    
jobs:
    deploy:
        name: Deploy app to Fly.io
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        