---
name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy app to Fly.io
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Deploy
              run: flyctl deploy --remote-only
              working-directory: src
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        